---
abstract: 'IRC plugin that fetches random TIL headlines from reddit.com/r/TodayILearned'
author:
  - 'Curtis Brandt, C<< <curtis at cpan.org> >>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.019
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-WWW-Reddit-TIL
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojo::UserAgent: 0
  POE::Component::IRC::Plugin: 0
  WWW::Shorten::Bitly: 1.17
  WWW::Shorten::Simple: 0.01
  perl: 5.010
resources:
  bugtracker: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Reddit-TIL/issues
  homepage: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Reddit-TIL
  repository: https://github.com/aggrolite/POE-Component-IRC-Plugin-WWW-Reddit-TIL.git
version: 0.06
x_contributors:
  - 'Curtis Brandt <curtisjbrandt@gmail.com>'
